### ISSUE TITLE
Unauthorized Request Error

### ISSUE THREAD

**Issue by akshalaby** [apideck-libraries/react-vault#34]
I followed [this guide](https://developers.apideck.com/guides/react-vault) to create sessions using the sdk and add the Vault component, but when I'm getting 401 unauthorized responses.

![image](https://user-images.githubusercontent.com/3112658/156069074-338edf85-7955-4b00-920c-74c8ff4a1a03.png)

In the network tab of the developer console, I'm seeing the /connections request failing
**Request URL:** https://unify.apideck.com/vault/connections
**Request Method:** GET
**Status Code:** 401 
**Relevant Headers:**
authorization: Bearer <session_token>
x-apideck-app-id: <app_id>
x-apideck-auth-type: JWT
x-apideck-consumer-id: <customer_identifier>
**Response:** {"status_code":401,"error":"Unauthorized","type_name":"UnauthorizedError","message":"Unauthorized Request","detail":"Invalid Authorization Token","ref":"https://developers.apideck.com/errors#unauthorizederror"}

I followed the guide quite closely.  The session is created successfully and the token seems valid.  Here is the react component code:
```
import { Vault } from '@apideck/react-vault';
import { Button } from '@chakra-ui/react';
import { useActiveVendorId } from 'hooks/useActiveVendor';
import { useState } from 'react';
import '@apideck/react-vault/dist/styles.css'; // If not using Tailwind CSS

const IntegrateAPIDeckVaultCard = () => {
  const vendorId = useActiveVendorId();
  const [isLoading, setIsLoading] = useState(false);
  const [openVault, setOpenVault] = useState(false);
  const [token, setToken] = useState('');

  const toggleVault = () => {
    setOpenVault(!openVault);
  };

  const createSession = async () => {
    setIsLoading(true);
    try {
      const raw = await fetch('/api/apideck/session', {
        method: 'POST',
        body: JSON.stringify({ vendorId }),
      });
      const response = await raw.json();
      if (response.session_token) {
        setToken(response.session_token);
        setOpenVault(true);
      }
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="flex items-center space-x-3">
      <Button
        onClick={token ? toggleVault : createSession}
        isLoading={isLoading}
      >
        Open APIDECK Vault
      </Button>
      <Vault
        jwt={token}
        appId={`${process.env.NEXT_PUBLIC_APIDECK_APP_ID}`}
        consumerId={`${vendorId}`}
        open={openVault}
        onClose={toggleVault}
      />
    </div>
  );
};

export default IntegrateAPIDeckVaultCard;
```

**Comment by jakeprins** [comment]
Looking at the code it seems like it should work. The error indicates that something is off with the session. Make sure the `appId` and `consumerId` that are being used to create the session are the same as the ones you provide to the component. So in the code from the guide for creating a session, you should replace `test-consumer` with the `vendorId` you added to the body.

**Comment by akshalaby** [comment]
Thank you!  In fact, the consumerId was slightly different in session creation than the one use in the Vault component.  After getting them to be the same, auth issue went away.
