### ISSUE TITLE
Vault: Add prop to remove logo on top of modal

### ISSUE THREAD

**Issue by jakeprins** [apideck-libraries/react-vault#69]
Optionally add logo URL to show on top of the modal.

If none is provided, it shouldn't show a logo and UI should be adjusted. 

Linked to the Xero App approval process for the partner.

**Comment by Gdewilde** [comment]
@jakeprins Thanks for fixing this. Is this listed in the README?

**Comment by jakeprins** [comment]
fyi Instead of a prop, it uses the `theme` object which could have the `logo` property. I've updated the readme's to include that.

**Comment by jakeprins** [comment]
It's a setting you need to set through the session, so it depends on what image URL is provided. If nothing is provided it doesn't show anything and otherwise, the image that you have provided is to be shown there. Like on the website, we provide a logo, so it looks like it always did:
![CleanShot 2023-01-20 at 15 21 28](https://user-images.githubusercontent.com/17762366/213721564-247f9db7-bff5-448b-99a0-50f9eb295d60.png)

Only the Platform API doesn't apply the theme object yet when provided during the creation of the session, which I created an issue for https://github.com/apideck-io/platform-api/issues/276

**Comment by Gdewilde** [comment]
Ok, thanks for the explainer. Great work.
